// <auto-generated />
using CalculoBasesAIE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculoBasesAIE.Migrations
{
    [DbContext(typeof(BaseHormigonContext))]
    [Migration("20250620143823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculoBasesAIE.Models.BaseHormigon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.HasKey("Id");

                    b.ToTable("BasesHormigon");
                });

            modelBuilder.Entity("CalculoBasesAIE.Models.BaseHormigon", b =>
                {
                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "AnchoColumnaX", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "AnchoColumnaY", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "CargaAdmisible", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "DiametroBarrasX", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "DiametroBarrasY", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "EsfuerzoAxil", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "NivelFundacion", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "PesoEspecificoHormigon", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "PesoEspecificoSuelo", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "PorcentajeCargaD", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "PorcentajeCargaL", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "RecubrimientoHormigon", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "ResistenciaCaracteristicaHormigon", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "TensionFluenciaAcero", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.Navigation("AnchoColumnaX")
                        .IsRequired();

                    b.Navigation("AnchoColumnaY")
                        .IsRequired();

                    b.Navigation("CargaAdmisible")
                        .IsRequired();

                    b.Navigation("DiametroBarrasX")
                        .IsRequired();

                    b.Navigation("DiametroBarrasY")
                        .IsRequired();

                    b.Navigation("EsfuerzoAxil")
                        .IsRequired();

                    b.Navigation("NivelFundacion")
                        .IsRequired();

                    b.Navigation("PesoEspecificoHormigon")
                        .IsRequired();

                    b.Navigation("PesoEspecificoSuelo")
                        .IsRequired();

                    b.Navigation("PorcentajeCargaD")
                        .IsRequired();

                    b.Navigation("PorcentajeCargaL")
                        .IsRequired();

                    b.Navigation("RecubrimientoHormigon")
                        .IsRequired();

                    b.Navigation("ResistenciaCaracteristicaHormigon")
                        .IsRequired();

                    b.Navigation("TensionFluenciaAcero")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
