// <auto-generated />
using CalculoBasesAIE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalculoBasesAIE.Migrations
{
    [DbContext(typeof(BaseHormigonContext))]
    [Migration("20251103000536_Agregado_Computo")]
    partial class Agregado_Computo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CalculoBasesAIE.Models.BaseHormigon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BasesHormigon");
                });

            modelBuilder.Entity("CalculoBasesAIE.Models.BaseHormigonArmadura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CantidadBarrasX")
                        .HasColumnType("float");

                    b.Property<double>("CantidadBarrasY")
                        .HasColumnType("float");

                    b.Property<double>("SeparacionBarrasX")
                        .HasColumnType("float");

                    b.Property<double>("SeparacionBarrasY")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BasesHormigonArmaduras");
                });

            modelBuilder.Entity("CalculoBasesAIE.Models.BaseHormigonComputo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("LongitudBarrasX")
                        .HasColumnType("float");

                    b.Property<double>("LongitudBarrasY")
                        .HasColumnType("float");

                    b.Property<double>("MontoAcero")
                        .HasColumnType("float");

                    b.Property<double>("MontoExcavacion")
                        .HasColumnType("float");

                    b.Property<double>("MontoHormigon")
                        .HasColumnType("float");

                    b.Property<double>("PesoBarrasX")
                        .HasColumnType("float");

                    b.Property<double>("PesoBarrasY")
                        .HasColumnType("float");

                    b.Property<double>("VolumenExcavacion")
                        .HasColumnType("float");

                    b.Property<double>("VolumenHormigon")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BasesHormigonComputos");
                });

            modelBuilder.Entity("CalculoBasesAIE.Models.BaseHormigonCuantia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("AreaAceroX")
                        .HasColumnType("float");

                    b.Property<double>("AreaAceroY")
                        .HasColumnType("float");

                    b.Property<double>("CargaMayorada")
                        .HasColumnType("float");

                    b.Property<double>("CuantiaAdoptadaX")
                        .HasColumnType("float");

                    b.Property<double>("CuantiaAdoptadaY")
                        .HasColumnType("float");

                    b.Property<double>("CuantiaCalculoX")
                        .HasColumnType("float");

                    b.Property<double>("CuantiaCalculoY")
                        .HasColumnType("float");

                    b.Property<double>("CuantiaMaxima")
                        .HasColumnType("float");

                    b.Property<double>("CuantiaMecanicaX")
                        .HasColumnType("float");

                    b.Property<double>("CuantiaMecanicaY")
                        .HasColumnType("float");

                    b.Property<double>("CuantiaMinima")
                        .HasColumnType("float");

                    b.Property<double>("EsfuerzoAxilMayorado")
                        .HasColumnType("float");

                    b.Property<double>("FactorAdimensionalX")
                        .HasColumnType("float");

                    b.Property<double>("FactorAdimensionalY")
                        .HasColumnType("float");

                    b.Property<double>("MomentoMayoradoX")
                        .HasColumnType("float");

                    b.Property<double>("MomentoMayoradoY")
                        .HasColumnType("float");

                    b.Property<double>("MomentoNominalX")
                        .HasColumnType("float");

                    b.Property<double>("MomentoNominalY")
                        .HasColumnType("float");

                    b.Property<bool>("VerificaCuantiaMaxima")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BasesHormigonCuantias");
                });

            modelBuilder.Entity("CalculoBasesAIE.Models.BaseHormigonDiametrosBarras", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("DiametroX")
                        .HasColumnType("float");

                    b.Property<double>("DiametroY")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BasesHormigonDiametrosBarras");
                });

            modelBuilder.Entity("CalculoBasesAIE.Models.BaseHormigonDimensiones", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<double>("AnchoX")
                        .HasColumnType("float");

                    b.Property<double>("AnchoY")
                        .HasColumnType("float");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<bool>("VerificaVuelos")
                        .HasColumnType("bit");

                    b.Property<double>("VueloX")
                        .HasColumnType("float");

                    b.Property<double>("VueloY")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BasesHormigonDimensiones");
                });

            modelBuilder.Entity("CalculoBasesAIE.Models.BaseHormigonEsfuerzos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CorteX")
                        .HasColumnType("float");

                    b.Property<double>("CorteY")
                        .HasColumnType("float");

                    b.Property<double>("MomentoX")
                        .HasColumnType("float");

                    b.Property<double>("MomentoY")
                        .HasColumnType("float");

                    b.Property<double>("Normal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BasesHormigonEsfuerzos");
                });

            modelBuilder.Entity("CalculoBasesAIE.Models.BaseHormigonVerificacionCorte", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("CargaTotal")
                        .HasColumnType("float");

                    b.Property<bool>("CumpleVerificacion")
                        .HasColumnType("bit");

                    b.Property<double>("ResistenciaDisenoX")
                        .HasColumnType("float");

                    b.Property<double>("ResistenciaDisenoY")
                        .HasColumnType("float");

                    b.Property<double>("ResistenciaNominalX")
                        .HasColumnType("float");

                    b.Property<double>("ResistenciaNominalY")
                        .HasColumnType("float");

                    b.Property<double>("ResistenciaRequeridaX")
                        .HasColumnType("float");

                    b.Property<double>("ResistenciaRequeridaY")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BasesHormigonVerificacionCorte");
                });

            modelBuilder.Entity("CalculoBasesAIE.Models.BaseHormigonVerificacionPunzonado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("B")
                        .HasColumnType("float");

                    b.Property<double>("B0")
                        .HasColumnType("float");

                    b.Property<double>("CargaTotal")
                        .HasColumnType("float");

                    b.Property<bool>("CumpleVerificacion")
                        .HasColumnType("bit");

                    b.Property<double>("EsfuerzoAxilMayorado")
                        .HasColumnType("float");

                    b.Property<double>("ResistenciaDiseno")
                        .HasColumnType("float");

                    b.Property<double>("ResistenciaNominal")
                        .HasColumnType("float");

                    b.Property<double>("ResistenciaRequerida")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BasesHormigonVerificacionPunzonado");
                });

            modelBuilder.Entity("CalculoBasesAIE.Models.BaseHormigonVerificaciones", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double>("AsentamientoMaximo")
                        .HasColumnType("float");

                    b.Property<double>("AsentamientoMedio")
                        .HasColumnType("float");

                    b.Property<double>("AsentamientoMinimo")
                        .HasColumnType("float");

                    b.Property<double>("CoeficienteSeguridadDeslizamiento")
                        .HasColumnType("float");

                    b.Property<double>("CoeficienteSeguridadVuelco")
                        .HasColumnType("float");

                    b.Property<double>("DistorsionAngular")
                        .HasColumnType("float");

                    b.Property<double>("ExcentricidadX")
                        .HasColumnType("float");

                    b.Property<double>("ExcentricidadY")
                        .HasColumnType("float");

                    b.Property<double>("TensionMaximaX")
                        .HasColumnType("float");

                    b.Property<double>("TensionMaximaY")
                        .HasColumnType("float");

                    b.Property<double>("TensionMinimaX")
                        .HasColumnType("float");

                    b.Property<double>("TensionMinimaY")
                        .HasColumnType("float");

                    b.Property<bool>("VerificaAsentamientoDiferencial")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificaAsentamientoMedio")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificaDeslizamiento")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificaTensionAdmisible")
                        .HasColumnType("bit");

                    b.Property<bool>("VerificaVuelco")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BasesHormigonVerificaciones");
                });

            modelBuilder.Entity("CalculoBasesAIE.Models.BaseHormigon", b =>
                {
                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "AnchoColumnaX", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "AnchoColumnaY", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "CargaAdmisible", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "CoeficienteEsponjamiento", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "CorteX", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "CorteY", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "CostoKgAcero", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "CostoM3Excavacion", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "CostoM3Hormigon", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "DiametroBarrasX", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "DiametroBarrasY", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "EsfuerzoAxil", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "ModuloBalasto", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "MomentoX", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "MomentoY", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "NivelFundacion", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "PesoEspecificoHormigon", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "PesoEspecificoSuelo", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "PorcentajeCargaD", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "PorcentajeCargaL", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "RecubrimientoHormigon", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "ResistenciaCaracteristicaHormigon", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.OwnsOne("CalculoBasesAIE.Models.ValueUnitPair", "TensionFluenciaAcero", b1 =>
                        {
                            b1.Property<long>("BaseHormigonId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Unidad")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<double>("Valor")
                                .HasColumnType("float");

                            b1.HasKey("BaseHormigonId");

                            b1.ToTable("BasesHormigon");

                            b1.WithOwner()
                                .HasForeignKey("BaseHormigonId");
                        });

                    b.Navigation("AnchoColumnaX")
                        .IsRequired();

                    b.Navigation("AnchoColumnaY")
                        .IsRequired();

                    b.Navigation("CargaAdmisible")
                        .IsRequired();

                    b.Navigation("CoeficienteEsponjamiento")
                        .IsRequired();

                    b.Navigation("CorteX")
                        .IsRequired();

                    b.Navigation("CorteY")
                        .IsRequired();

                    b.Navigation("CostoKgAcero")
                        .IsRequired();

                    b.Navigation("CostoM3Excavacion")
                        .IsRequired();

                    b.Navigation("CostoM3Hormigon")
                        .IsRequired();

                    b.Navigation("DiametroBarrasX")
                        .IsRequired();

                    b.Navigation("DiametroBarrasY")
                        .IsRequired();

                    b.Navigation("EsfuerzoAxil")
                        .IsRequired();

                    b.Navigation("ModuloBalasto")
                        .IsRequired();

                    b.Navigation("MomentoX")
                        .IsRequired();

                    b.Navigation("MomentoY")
                        .IsRequired();

                    b.Navigation("NivelFundacion")
                        .IsRequired();

                    b.Navigation("PesoEspecificoHormigon")
                        .IsRequired();

                    b.Navigation("PesoEspecificoSuelo")
                        .IsRequired();

                    b.Navigation("PorcentajeCargaD")
                        .IsRequired();

                    b.Navigation("PorcentajeCargaL")
                        .IsRequired();

                    b.Navigation("RecubrimientoHormigon")
                        .IsRequired();

                    b.Navigation("ResistenciaCaracteristicaHormigon")
                        .IsRequired();

                    b.Navigation("TensionFluenciaAcero")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
